name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry install
    - name: Publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN_PYCWATCH_LIB }}
      run: |
        ./scripts/publish.sh lib

  publish-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install -U pip poetry
        poetry install
    - name: Publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN_PYCWATCH_CLI }}
      run: |
        ./scripts/publish.sh cli
